### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by curiousdannii** [kmill/zmach#1]
I've just discovered this repo, and I'm very impressed! I have been [wanting to adapt the relooper algorithm for my ZVM engine](https://github.com/curiousdannii/ifvms.js/issues/4) for a long time.

Could you give a little bit of a more detailed overview of how you've done it? For example, is each Z-Machine instruction a relooper block (Simple, Loop etc) or do you bundle them up first?

How does the order go, is it z-code -> relooper blocks -> IR -> JS? 

I'd also be interested to hear about your try/catch function call wrapping.

**Comment by kmill** [comment]
I can give a little detail right now.

When get_routine is called and it needs to be recompiled, these are the main steps:
1. The disassembler disassembles everything which is reachable from the address of the routine.  This uses a certain "destination-based" translation to convert the opcodes into a smaller IR while trying to avoid too many temporary variables ("`op_gensym`" creates new names for them).
2. The instructions are broken into basic blocks, which are sequences of instructions which end in a branch instruction, and which are only ever entered at the beginning of the block.  This gives a routine's control flow graph.  "`simple_pop_remove`" replaces push/pop pairs with a move.
3. The relooper algorithm gets ahold of this graph and creates a tree of Simple, Multiple, and Loop nodes.  I used a modification of the Emscripten whitepaper's algorithm which seemed to make more sense to me.  I've been thinking of describing the algorithm at some point, but the gist is that it involves using some somewhat arbitrary heuristics to recursively breaking apart the control flow graph, replacing branches with continues and breaks, while creating a corresponding tree structure.
4. The result of this algorithm needs another pass to eliminate future switch statements, which I called "scavenging."  A simple block which is followed by a multiple will try to scavenge branches from the Multiple to create if statements, if I remember correctly.  This is in `build_code`, and now we have a tree-based IR.
5. There are a few optimizations done to it, but they're basically just there to make the code look nice.  For instance, removing unnecessary breaks and continues, and removing unnecessary setting of the `__label__` variable.
6. convert_routine_to_js takes the tree IR and converts it to javascript.  There are 16 statement-level IR instructions, and a larger number of expression-level IR instructions.  There is some complexity in the code generator for expressions which I can't completely remember what it was for, but it might be for pausing.  One feature is that local variables for a z-machine routine turn into actual local variables in javascript.  Another feature is that, if it is needed, the try/catch pausing code gets added (explained later).

The routine gets installed in a table, and every routine accessible from this routine has a stub installed into the table that does the above compilation stuff on demand.  But, in the background the entire set of transitively accessible functions will be recompiled --- this will eliminate try/catch code from functions which will provably never need to pause, which is good because V8 can't (as far I've heard) optimize code contained within a try block.

Now to try to describe the try/catch method for pausing.  The problem any javascript JIT must face is that the resulting code must be non-blocking so that control can pass back to the UI thread.  One way to handle this is to use generator-based coroutines, but I figured that would incur a lot of overhead at every single call site.

The main idea of the try/catch method is that a function sets a continuation variable, which I called `__cont__` in the generated javascript, just before doing any operation which might conceivably cause the machine to pause, for instance a read instruction or calling a function which itself might pause.  The continuation variable contains just enough information for how to continue from that point: the next program counter and whether the result is stored in a register or pushed to the stack.  If the following operation does indeed want to pause execution, it throws a PauseException, and then the routine catches the PauseException, and creates a CallFrame to reify the stack.  Here's an example:
```
    if (x instanceof PauseException) {
      throw new PauseException(x.action, x.args, new CallFrame(__numargs__, [arg_0,arg_1,arg_2,arg_3,arg_4,arg_5], Array.from(__stack__), __cont__, x.frame));
    } [...]
```
In this case, there were 6 local variables and a local `__stack__` variable the optimizations couldn't figure out how to remove.

The outer interpreter ultimately catches the PauseException, and does something based on the requested action.  For instance, if it is "read" then the interpreter tells the display to get a line of input and then call a callback.  The callback resumes the interpreter, and the interpreter passes the CallFrame to a compiled continuation function, where the continuation function is selected by the `__cont__` data.  Continuations are almost the same as routines, and are compiled in almost exactly the same way: the program counter in the `__cont__` is taken to be the starting instruction for disassembly, but then later the function is instead compiled to take a CallFrame to resume execution using the resume IR.  (So, a trick here is that instead of trying to resume the actual function from before, we pick up execution using a completely new function which has been compiled to start at the correct z-machine instruction.)

(After I came up with this technique, I found basically the same thing in a paper from a Scheme workshop on how to compile continuations to Javascript.)

**Comment by curiousdannii** [comment]
Thanks, there are lots of insights here!

>The disassembler disassembles everything which is reachable from the address of the routine. This uses a certain "destination-based" translation to convert the opcodes into a smaller IR while trying to avoid too many temporary variables ("op_gensym" creates new names for them).

What are the temporary variables for? I have only had to use them once, which is when storing to the stack so that the stack pointer doesn't get confused. (`t=xxx;s[sp++]=t`)

**Comment by kmill** [comment]
The "destination-based" translation is where you translate instructions into something with the type `{setup:[statement], val:expr}`, which is pretty convenient for keeping track of side effects (like stack manipulation) when you translate an opcode.  For sake of notation, let `D` be that type.  The function `cbinds` takes a `[D]` and a function `[expr] -> D` and returns a `D` that runs all of the statements in sequence, followed by whatever the function does with the resulting expressions.  For instance, if you have an opcode which sums the top two elements of the stack and stores it into local 1, it creates two `D`s which represent popping the stack (like `{setup:[["pop", ["var", "tmp1"]]], val:["var", "tmp1"]}` and `{setup:[["pop", ["var", "tmp2"]]], val:["var", "tmp2"]}`) and then uses `cbinds` with an appropriate function to create `{setup:[["pop", ["var", "tmp1"]], ["pop", ["var", "tmp1"]], ["set", ["local", 0], ["+", ["var", "tmp1"], ["var", "tmp2"]]]], val:null}`.

The cases of creating temporary variables are popping, indirect variable access (that feature where a variable is referenced by variable number -- this gets compiled into a switch statement with the temporary variable being set in each case, though I don't think I've ever witnessed this feature get used), indirect variable setting, and returning a popped value.  Basically, for maintaining sanity, expressions in the AST are not allowed to have side effects.  Side effects are reserved for statements.

One side benefit to doing it this way is it is easy to eliminate push/pop pairs. [`simple_pop_remove`](https://github.com/kmill/zmach/blob/master/zmach.js#L251) turns `[["push", x], ["pop", y]]` into `[["set", y, x]]`.  (That function also does something with `"contstack"`, which is for calling a function which might pause execution but which we should remember pushes its result on the stack.  We don't actually need to push the result onto the stack, though, so it has a field (usually `null`) to say [where to store the result](https://github.com/kmill/zmach/blob/master/zmach.js#L958).)

**Comment by curiousdannii** [comment]
ZVM is much more direct in its code generation. I'll have to consider how much more indirection/abstraction I want. 

>Basically, for maintaining sanity, expressions in the AST are not allowed to have side effects. Side effects are reserved for statements.

What does expression and statement mean in this context? Are statements just the parts that store instruction results?

**Comment by kmill** [comment]
I'm meaning them roughly how they mean in most languages: statements are control flow and contain expressions which can evaluate to a value.  Here's a brief overview of the AST nodes: 

The AST statements are `block`, `switch`, `loop`, `if`, `break`, `continue`, `return`, `quit`, `cont` (a pausable set), `contstack` (a pausable push), `push`, `pop`, `set`, `get_var` (for getting a variable by variable index), `ignore` (run expression, dropping value), `restart` (to restart the game)

The AST expressions are `lit`, `string`, `global`, `local`, `var`, `peek`, `call`, `indcall`, `extern`, `resumeframe`, `or`, `and`, `|`, `&`, `===`, `!==`, `<`, `>`, `<=`, `>=`, `+`, `-`, `*`, `div`, `mod`, `not`

The AST lvalues (appearing in set and pop) are `local`, `global`, and `var`, where `var` is for temporary variables.

Opcodes are directly decoded into basic blocks of AST statements, along with `branch` statements, and then the relooper-related algorithms convert the basic blocks into `block`, `switch`, `loop`, and `if` statements, replacing the branches with `break`s and `continue`s (or nothing if the branch is just a fall-through).

The design of the AST is to be close to Javascript so that it's relatively straightforward to translate to raw Javascript while being somewhat amenable to optimization.  However, the optimizations I do beyond push/pop elimination are not particularly useful for an emulator --- I just wanted to study the translated code.

(It appears I was lying about expressions not having side effects, since `call`, `indcall`, and `extern` can definitely have side-effects.  To fix what I said: it is better to keep one side effect per expression. Having push/pop at the statement level just makes it easier to detect when they can be eliminated.)

**Comment by curiousdannii** [comment]
Thanks, that's quite helpful. Consider this question issue closed now.

If you ever wanted to contribute to ZVM I'd be happy to have you! :)
